<?php
require_once __DIR__ . '/includes/auth.php';
$pageTitle = 'Houses - My Nyumba';
require __DIR__ . '/includes/header.php';
$houses=[
 ['name'=>'Modern 2 Bedroom Apartment','location'=>'Rongai, Kajiado','rent'=>'KES 28,000','beds'=>2,'baths'=>2,'area'=>'850 sq ft','status'=>'Available','image'=>'assets/img/slides-1.jpg'],
 ['name'=>'Family 3 Bedroom House','location'=>'Kiserian, Kajiado','rent'=>'KES 42,000','beds'=>3,'baths'=>2,'area'=>'1,450 sq ft','status'=>'Occupied','image'=>'assets/img/kitchen.jpg'],
 ['name'=>'Executive Bedsitter','location'=>'Karen, Nairobi','rent'=>'KES 18,000','beds'=>1,'baths'=>1,'area'=>'420 sq ft','status'=>'Available','image'=>'assets/img/card.jpg'],
 ['name'=>'4 Bedroom Townhouse','location'=>'Karen, Nairobi','rent'=>'KES 95,000','beds'=>4,'baths'=>4,'area'=>'2,800 sq ft','status'=>'Maintenance','image'=>'assets/img/slides-3.jpg'],
 ['name'=>'Spacious 1 Bedroom','location'=>'Ngong, Kajiado','rent'=>'KES 22,000','beds'=>1,'baths'=>1,'area'=>'620 sq ft','status'=>'Available','image'=>'assets/img/product-1.jpg'],
 ['name'=>'2 Bedroom Maisonette','location'=>'Kitengela, Kajiado','rent'=>'KES 35,000','beds'=>2,'baths'=>2,'area'=>'1,050 sq ft','status'=>'Occupied','image'=>'assets/img/product-2.jpg']
];
?>
<main id="main" class="main"><div class="pagetitle"><h1>Houses</h1><nav><ol class="breadcrumb"><li class="breadcrumb-item"><a href="index.php">Home</a></li><li class="breadcrumb-item">Properties</li><li class="breadcrumb-item active">Houses</li></ol></nav></div>
<section class="section"><div class="card mb-4"><div class="card-body"><div class="row align-items-center g-3"><div class="col-lg-5"><h5 class="card-title mb-1">Residential Houses</h5><p class="text-muted mb-0">Manage available, occupied and maintenance units.</p></div><div class="col-lg-7"><div class="d-flex flex-wrap justify-content-lg-end gap-2"><button class="filter-chip active">All 186</button><button class="filter-chip">Available 42</button><button class="filter-chip">Occupied 132</button><button class="filter-chip">Maintenance 12</button><a href="properties-listings.php" class="btn btn-primary btn-sm"><i class="bi bi-plus-lg"></i> Add House</a></div></div></div></div></div>
<div class="row g-4"><?php foreach($houses as $h): $statusClass=$h['status']==='Available'?'status-available':($h['status']==='Occupied'?'status-occupied':'status-maintenance'); ?><div class="col-xl-4 col-md-6"><div class="card property-card h-100 mb-0"><img src="<?= $h['image'] ?>" class="property-cover" alt="<?= htmlspecialchars($h['name']) ?>"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-2"><span class="status-pill <?= $statusClass ?>"><?= $h['status'] ?></span><button class="btn btn-sm btn-light"><i class="bi bi-three-dots"></i></button></div><h5 class="mb-1"><?= htmlspecialchars($h['name']) ?></h5><div class="property-meta mb-3"><i class="bi bi-geo-alt"></i> <?= htmlspecialchars($h['location']) ?></div><div class="d-flex gap-3 property-meta mb-3"><span><i class="bi bi-door-open"></i> <?= $h['beds'] ?> Beds</span><span><i class="bi bi-droplet"></i> <?= $h['baths'] ?> Baths</span><span><i class="bi bi-rulers"></i> <?= $h['area'] ?></span></div><div class="d-flex justify-content-between align-items-center border-top pt-3"><span class="property-price"><?= $h['rent'] ?><small class="text-muted fw-normal"> /month</small></span><a href="properties-listings.php" class="btn btn-outline-primary btn-sm">View details</a></div></div></div></div><?php endforeach; ?></div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?><?php require __DIR__ . '/includes/scripts.php'; ?></body></html>
