<?php
/**
 * ============================================================
 * PAGE: Sidebar
 * DESCRIPTION: Reusable application sidebar navigation.
 * ============================================================
 */

$currentPage=basename($_SERVER['PHP_SELF']); function navA($p){global $currentPage;return in_array($currentPage,(array)$p,true)?'':'collapsed';} ?>
<aside id="sidebar" class="sidebar"><ul class="sidebar-nav" id="sidebar-nav">
<li class="nav-heading">Overview</li><li class="nav-item"><a class="nav-link <?=navA('index.php')?>" href="index.php"><i class="bi bi-grid"></i><span>Dashboard</span></a></li>
<li class="nav-heading">Properties</li><li class="nav-item"><a class="nav-link <?=navA(['property-create.php','property-edit.php','property-view.php'])?>" href="properties.php"><i class="bi bi-building-add"></i><span>Property Management</span></a></li><li class="nav-item"><a class="nav-link <?=navA('properties.php')?>" href="properties.php"><i class="bi bi-buildings"></i><span>Properties</span></a></li><li class="nav-item"><a class="nav-link <?=navA('houses.php')?>" href="houses.php"><i class="bi bi-house"></i><span>Houses / Units</span></a></li><li class="nav-item"><a class="nav-link <?=navA('listings.php')?>" href="listings.php"><i class="bi bi-megaphone"></i><span>Listings</span></a></li>
<li class="nav-heading">Tenants</li><li class="nav-item"><a class="nav-link <?=navA('tenants.php')?>" href="tenants.php"><i class="bi bi-people"></i><span>Tenants</span></a></li><li class="nav-item"><a class="nav-link <?=navA('applications.php')?>" href="applications.php"><i class="bi bi-person-check"></i><span>Applications</span></a></li>
<li class="nav-heading">Leases</li><li class="nav-item"><a class="nav-link <?=navA('leases.php')?>" href="leases.php"><i class="bi bi-file-earmark-text"></i><span>Leases</span></a></li>
<li class="nav-heading">Finance</li><li class="nav-item"><a class="nav-link <?=navA('invoices.php')?>" href="invoices.php"><i class="bi bi-receipt"></i><span>Invoices</span></a></li><li class="nav-item"><a class="nav-link <?=navA('receipts.php')?>" href="receipts.php"><i class="bi bi-file-earmark-check"></i><span>Receipts</span></a></li><li class="nav-item"><a class="nav-link <?=navA('expenses.php')?>" href="expenses.php"><i class="bi bi-cash-stack"></i><span>Expenses</span></a></li>
<li class="nav-heading">Utilities</li><li class="nav-item"><a class="nav-link <?=navA(['utilities.php','utility-create.php','utility-edit.php','utility-view.php','utility-readings.php','utility-reading-create.php','utility-reading-edit.php','property-utilities.php','property-utility-edit.php'])?>" href="utilities.php"><i class="bi bi-lightning-charge"></i><span>Utilities</span></a></li>
<li class="nav-heading">Operations</li><li class="nav-item"><a class="nav-link <?=navA('maintenance.php')?>" href="maintenance.php"><i class="bi bi-tools"></i><span>Maintenance</span></a></li><li class="nav-item"><a class="nav-link" href="messages.php"><i class="bi bi-chat-dots"></i><span>Messages</span></a></li><li class="nav-item"><a class="nav-link" href="notifications.php"><i class="bi bi-bell"></i><span>Notifications</span></a></li>
<li class="nav-heading">Reports</li><li class="nav-item"><a class="nav-link <?=navA('reports.php')?>" href="reports.php"><i class="bi bi-bar-chart"></i><span>Reports</span></a></li><li class="nav-item"><a class="nav-link <?=navA('owners.php')?>" href="owners.php"><i class="bi bi-person-vcard"></i><span>Property Owners</span></a></li>
<li class="nav-heading">Administration</li><li class="nav-item"><a class="nav-link <?=navA(['admins.php','admin-create.php','admin-edit.php'])?>" href="admins.php"><i class="bi bi-shield-lock"></i><span>Administrators</span></a></li><li class="nav-item"><a class="nav-link" href="audit-logs.php"><i class="bi bi-clock-history"></i><span>Audit Logs</span></a></li><li class="nav-item"><a class="nav-link" href="settings.php"><i class="bi bi-gear"></i><span>Settings</span></a></li>
</ul></aside>